enum RequestStatus {
  REQUEST_LOADING = "REQUEST_LOADING",
  REQUEST_FAILED = "REQUEST_FAILED",
  REQUEST_LOADED = "REQUEST_LOADED",
  REQUEST_NOT_LOADED = "REQUEST_NOT_LOADED",
}

export default RequestStatus;
