enum SCREEN_NAMES {
  LOGIN = "LOGIN",
  LOCATION = "LOCATION",
  ORDER = "ORDER",
  ROOT = "ROOT",
  USER_REQUIRED_FIELDS_FORM = "USER_REQUIRED_FIELDS_FORM",
  VERIFY_CODE = "VERIFY_CODE",
}

export default SCREEN_NAMES;
