enum SCREEN_NAMES {
  ADD_ADDRESS = 'ADD_ADDRESS',
  LOGIN = 'LOGIN',
  LOCATION = 'LOCATION',
  ORDER = 'ORDER',
  ROOT = 'ROOT',
  SELECT_ADDRESS = 'SELECT_ADDRESS',
  USER_REQUIRED_FIELDS_FORM = 'USER_REQUIRED_FIELDS_FORM',
  VERIFY_CODE = 'VERIFY_CODE',
}

export default SCREEN_NAMES;
