FROM node:lts
WORKDIR /app
COPY --chown=node:node ./package*.json ./
RUN npm install
COPY --chown=node:node . .
RUN npm run build:qa

FROM nginx
EXPOSE 80
COPY --chown=nginx:nginx --from=0 /app/dist /usr/share/nginx/html