apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-api
  template:
    metadata:
      labels:
        app: delivery-api
    spec:
      containers:
        - name: delivery-api
          image: registry.gitlab.com/edenjiga1/delivery-app/delivery-api
          imagePullPolicy: Always
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 200Mi
          env:
            - name: TZ
              value: America/Bogota
            - name: PRODUCT_API_URL
              value: http://products-srv:1337
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: MONGO_URL
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: AWS_REGION
            - name: AWS_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: AWS_CREDENTIALS
            - name: AWS_SHARED_CREDENTIALS_FILE
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: AWS_SHARED_CREDENTIALS_FILE
            - name: AWS_PINPOINT_ID
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: AWS_PINPOINT_ID
            - name: PRODUCT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: PRODUCT_API_TOKEN
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: JWT_SECRET_KEY
            - name: WOMPI_URL
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: WOMPI_URL
            - name: WOMPI_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: WOMPI_PUBLIC_KEY
            - name: WOMPI_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: WOMPI_PRIVATE_KEY
            - name: WOMPI_EVENTS_KEY
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: WOMPI_EVENTS_KEY
            - name: HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: HASH_SALT
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: delivery-secrets
                  key: NATS_CLUSTER_ID
            - name: NATS_STREAM_URL
              value: http://nats-srv:4222

            - name: REDIS_URL
              value: http://redis:6379

      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-api-srv
spec:
  selector:
    app: delivery-api
  ports:
    - name: delivery-api
      protocol: TCP
      port: 8000
      targetPort: 8000
---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: php-apache
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: delivery-api-depl
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#     - type: Resource
#       resource:
#         name: memory
#         target:
#           type: Utilization
#           averageUtilization: 50
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: delivery-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: delivery-api-depl
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
