apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: registry.gitlab.com/edenjiga1/delivery-app/products-api
          imagePullPolicy: Always
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
            requests:
              memory: 150Mi
              cpu: 100m
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_HOST
            - name: DATABASE_SRV
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_SRV
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_SSL
              value: "true"
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: AWS_BUCKET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: AWS_ACCESS_SECRET
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 1337
      targetPort: 1337

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-products-depl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: products-depl
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
