enum SOCKET_EVENTS {
  ORDER_UPDATED = "ORDER_UPDATED",
  ORDER_CREATED = "ORDER_CREATED",
  SETTING_MOBILE_APP_STAY_OPEN_UPDATED = "SETTING_MOBILE_APP_STAY_OPEN_UPDATED",
}

export { SOCKET_EVENTS };
