version: "3"
services:
  strapi:
    image: strapi/strapi
    container_name: delivery-product-api-strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      AWS_REGION: us-east-1
      AWS_BUCKET: delivery-app-tur
      AWS_ACCESS_KEY_ID: AKIARVE4WCVDAT5BC67A
      AWS_ACCESS_SECRET: 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
    volumes:
      - ./:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    ports:
      - "27018:27017"
    # volumes:
    #   - ./data:/data/db
