apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: edenjiga/delivery-products-api
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_URI
            - name: DATABASE_SSL
              value: true

---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 1337
      targetPort: 1337
