apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - secretName: kanguroo-com-tls
      hosts:
        - qa.kanguroo.xyz
        - qa.dashboard.kanguroo.xyz
        - qa.strapi.kanguroo.xyz
  rules:
    - host: qa.kanguroo.xyz
      http:
        paths:
          - path: /socket.io
            backend:
              serviceName: socket-api-srv
              servicePort: 8002
          - path: /(.*)
            backend:
              serviceName: delivery-api-srv
              servicePort: 8000
    - host: qa.strapi.kanguroo.xyz
      http:
        paths:
          - backend:
              serviceName: products-srv
              servicePort: 1337
    - host: qa.dashboard.kanguroo.xyz
      http:
        paths:
          - backend:
              serviceName: dashboard-srv
              servicePort: 80
