apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/use-regex: 'true'

spec:
  tls:
    - secretName: edgarjimenezg-com-tls
      hosts:
        - qa.edgarjimenezg.com
        - qa.strapi.edgarjimenezg.com
  rules:
    - host: qa.edgarjimenezg.com
      http:
        paths:
          - backend:
              serviceName: delivery-api-srv
              servicePort: 8000
    - host: qa.strapi.edgarjimenezg.com
      http:
        paths:
          - backend:
              serviceName: products-srv
              servicePort: 1337
