apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: registry.gitlab.com/edenjiga1/delivery-app/products-api:qa
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_HOST
            - name: DATABASE_SRV
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_SRV
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_SSL
              value: "true"
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: AWS_BUCKET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: products-secrets
                  key: AWS_ACCESS_SECRET
      imagePullSecrets:
        - name: registry-qa-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 1337
      targetPort: 1337
