name: deploy-producs-api-qa

on:
  push:
    branches: 
      - develop
    paths: 
     - 'products-api-strapi/**'
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd products-api-strapi/ && docker build -t edenjiga/product-api:qa
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
        
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/delivery/product-api:qa
