name: deploy-delivery-api:qa

on:
  push:
    branches:
      - develop
    paths:
      - 'delivery-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd delivery-api/ && docker build -t registry.digitalocean.com/delivery/delivery-api:qa .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/delivery/delivery-api:qa

      - name: Add DigitalOcean Cluster
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_QA_CLUSTER }}

      - name: Restar the service
        run: kubectl rollout restart deployment delivery-api-depl
