name: deploy-socket-api:qa

on:
  push:
    branches:
      - develop
    paths:
      - "socket-api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd socket-api/ && docker build -t registry.gitlab.com/edenjiga1/delivery-app/socket-api:qa .

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_QA_USERNAME }}
          password: ${{ secrets.GITLAB_QA_PASSWORD }}

      - name: Push image to GitLab Container Registry
        run: docker push registry.gitlab.com/edenjiga1/delivery-app/socket-api:qa

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Add DigitalOcean Cluster
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_QA_CLUSTER }}

      - name: Restar the service
        run: kubectl rollout restart deployment socket-api-depl
