name: deploy-delivery-api:prod

on:
  push:
    branches:
      - master
    paths:
      - "delivery-api/**"

defaults:
  run:
    working-directory: ./delivery-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t registry.gitlab.com/edenjiga1/delivery-app/delivery-api .

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      - name: Push image to Gitlab Container Registry
        run: docker push registry.gitlab.com/edenjiga1/delivery-app/delivery-api

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Add DigitalOcean Cluster
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_PROD_CLUSTER }}

      - name: Restar the service
        run: kubectl rollout restart deployment delivery-api-depl
