name: deploy-qa-manifests

on:
  push:
    branches:
      - develop
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        # run: doctl registry login --expiry-seconds 600
        run: doctl kubernetes cluster kubeconfig save 096a14ca-d608-4dcd-9cdb-ad92df4c55d9

      - name: Update infra folder
        run: kubectl apply -f infra/k8s-qa

        # run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s
